### ISSUE TITLE
Livedata +Viewmodel+Retrofit+gson error

### ISSUE THREAD

**Issue by emreerkahraman** [emreerkahraman/CryptoCurrencyExchange#1]
*Hİ I'm getting this error whatever i do whats wrong **

at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.emreerkahraman.cryptocurrencyexchange.model.Currency.getData()' on a null object reference at com.emreerkahraman.cryptocurrencyexchange.CurrencyListFragment.onActivityCreated(CurrencyListFragment.java:62)

**Comment by emreerkahraman** [comment]
@yigit help please

**Comment by yigit** [comment]
it is a null pointer exception.
`mViewModel.getCurrencyGsonLiveData().getValue()` is null.

**Comment by emreerkahraman** [comment]
ı know but data supposed to come
**Can you look at viewmodel**  
`public class CurrencyListViewModel extends ViewModel {

    private  LiveData<Currency> currencyLiveData=new MutableLiveData<>();
    private CurrencyListRepository currencyListRepository=new CurrencyListRepository();



    public LiveData<Currency> getCurrencyGsonLiveData() {
        if (currencyLiveData==null){
            currencyLiveData=currencyListRepository.getCurrencyList("TRY",6,"id","array");
        }
        return currencyLiveData;
    }
}`

**and repository real quick Did i implemented viewmodel + livedata wrong im using retrofit to fetch data and it seems in the log but not in fragment **


`public class CurrencyListRepository  {
    private ApiDataService apiDataService;
    private CoinMarketApiService apiService;
    private Call<Currency> call;



    public LiveData<Currency> getCurrencyList(final String mBase, Integer mLimit, String mSort, String mStructure){
        final MutableLiveData<Currency> data=new MutableLiveData<>();
        apiDataService=new ApiDataService();
        apiService=apiDataService.getRetrofit().create(CoinMarketApiService.class);

        call=apiService.getTicker(mBase,mLimit,mSort,mStructure);
        call.enqueue(new Callback<Currency>() {
            @Override
            public void onResponse(Call<Currency> call, Response<Currency> response) {


                Currency currency=response.body();
                data.postValue(currency);
                for (int i=0;i<currency.getData().size();i++){
                    Log.i("DATAS" ,currency.getData().get(i).getName()+" price :"+currency.getData().get(i).getQuotes().getBASE().getPrice());
//data comes
                }
            }

            @Override
            public void onFailure(Call<Currency> call, Throwable t) {

                Log.i("FAİL",":/");

            }
        });
        return data;

    }



}`
